name: Develop to Staging Merge CI

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: technote-space/assign-author@v1.2.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Source Code
        uses: actions/checkout@v2-beta
        with:
          ref: master

      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Pulling ${{ github.ref }} into Staging from Develop"
          body: ":crown: *An automated PR*"
          branch: "staging"
          commit-message: "Bringing in approved changes from develop to staging for UAT"