name: Develop to Staging Merge CI

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: technote-space/assign-author@v1.2.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Source Code
        uses: actions/checkout@v2-beta
        with:
          ref: master

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.0.2
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          base: staging
          title: 'Merging Approved Changes from Develop to Staging'
          body: >
            Merging Approved Changes from Develop to Staging.