name: CI

on:
  push:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
      
    - name: Install Dependencies
      working-directory: ./
      run: |
        ls
        npm install
        npm i eslint -g
        npm run lint
        npm run test
