name: CI

on:
  push:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Update npm
      run: npm install npm@latest -g  
    - name: Install Dependencies
      run: npm install
    - name: Run ESLint
      working-directory: ./CoachingApp
      run: npm run lint
    - name: Run CLI Tests
      run: npm run test
