name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node
      run: |
        sudo apt install curl
        curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        sudo apt install nodejs
        node --version
        npm --version
        ls
        sudo npm i npm -g
        sudo npm i eslint -g
      env:
        CI: true
    - name: NPM Install Packages
      working-directory: ./
      run: |
        ls
        echo $PWD
      env:
        CI: true 
