name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
      working-directory: ./
      run: |
        ls
        npm i npm -g
        npm i eslint -g
        npm install
        npm run lint
        npm run test
