name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Setup Node.js for use with actions
      uses: actions/checkout@v2-beta
    - name: NPM Install Packages
      working-directory: ./
      run: |
        npm install
        npm run lint
      env:
        CI: true 
