name: CI
//Eslinting & CLI Testing pushed branch for now. After review approval. Merge to Develop branch and Deploy in devcqref.web.app After review approval. Merge to Staging branch and Deploy in stagingcqref.web.app. Merge to Master and deploy in production env

on:
  push:
    branches:
    - *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.0
    - name: Run CLI Tests
      uses: npm run test
