name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Assign Author
      uses: technote-space/assign-author@v1.2.4
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      
    - name: Checkout Source Code
      uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.after }}
      
    - name: NPM Install Packages
      working-directory: ./
      run: |
        npm install
      env:
        CI: true 

    - name: Running Linter
      working-directory: ./
      run: npm run lint
      env:
        CI: true 

    - name: Running Cypress Test in CLI Mode
      working-directory: ./
      run: npm run test
      env:
        CI: true 

    - name: Deploy on Dev Server
      working-directory: ./
      run: npm run devdeploy
      env:
        CI: true 
    
    - name: Deploy on Staging Server
      working-directory: ./
      run: npm run stagingdeploy
      env:
        CI: true 
    
    - name: Automatically create review requests based on assignees
      uses: pullreminders/assignee-to-reviewer-action@v1.0.4
    
