name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Assign Author
      uses: technote-space/assign-author@v1.2.4
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      
    - name: Checkout Source Code
      uses: actions/checkout@v2-beta
      with:
        ref: ${{ github.event.after }}
      
    - name: NPM Install Packages
      working-directory: ./
      run: |
        npm install
      env:
        CI: true 

    - name: Running ESLinter to Find Errors
      working-directory: ./
      run: npm run lint
      env:
        CI: true
      
    - name: Running Cypress Test in CLI Mode
      working-directory: ./
      run: npm run test
      env:
        CI: true

    - name: Generate on Dev Server Code
      working-directory: ./
      run: |
        npm run removebuild
        npm run dev
        npm run copy
      env:
        CI: true

    - name: Deploy on DevServer
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:devcqref
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_KEY }}
    
    - name: Audit DevServer URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://devcqref.web.app/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './lighthouse-reports'
    
    - name: Generate on Staging Server Code
      working-directory: ./
      run: |
        npm run removebuild
        npm run prod
        npm run copy
      env:
        CI: true
        
    - name: Audit StagingServer URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://devcqref.web.app/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './lighthouse-reports'

    - name: Deploy on Staging Server
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:stagingcqref
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_KEY }}
    
    - name: Automatically create review requests based on assignees
      uses: pullreminders/assignee-to-reviewer-action@v1.0.4
    
