name: Staging to Prod Merge CI

on:
  pull_request:
    types:
      - closed
    branches:
      - staging

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: technote-space/assign-author@v1.2.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Source Code
        uses: actions/checkout@v2-beta
        with:
          ref: master

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.0.2
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: staging
          base: master
          title: 'UAT Approved Changes from Staging Ready to Deploy into Production'
          body: >
            UAT Approved Changes from Staging Ready to Deploy into Production,
            Goto https://stagingcqref.web.app to Test the App and submit any issues via Logrocket.

      - name: Automatically create review requests based on assignees
        uses: pullreminders/assignee-to-reviewer-action@v1.0.4